extends Node2D


var dialouge_1=[
	{
	"Name": "MC",
	"Position": "1",
	"Text": "Ashton! Fight me!",
	"Choices": ["",""],
	},
	{"Name": "Ashton",
	"Position": "2",
	"Text": "Not this again, im taking a break right now",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "UGH but you're always busy or taking a break when I want to fight",
	"Choices": ["",""],
	},
	{"Name": "Ashton",
	"Position": "2",
	"Text": "Huh have you maybe ever thought about coming at different times then?",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "But I have! Ive come at so many different times but each time you seem to be conveniently occupied",
	"Choices": ["",""],
	},
		{"Name": "Ashton",
	"Position": "2",
	"Text": "You think that may say something as well?",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "Uh oh I see, I'm sorry for bothering you Ashton Ill leave now",
	"Choices": ["",""],
	},
		{"Name": "Ashton",
	"Position": "2",
	"Text": "Huh? Wait what? ",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "*Leaving*",
	"Choices": ["",""],
	},
	{"Name": "Ashton",
	"Position": "2",
	"Text": "Hey! Wait, why are you leaving?!",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "Uh… are you serious?",
	"Choices": ["",""],
	},
	{"Name": "Ashton",
	"Position": "2",
	"Text": "Yes",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "Oh my god you’re unbearable, of course Im leaving you basically just told me you hate me!",
	"Choices": ["",""],
	},
	{"Name": "Ashton",
	"Position": "2",
	"Text": "Uh when did I do that?",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "You’re kidding me right?",
	"Choices": ["",""],
	},
	{"Name": "Ashton",
	"Position": "2",
	"Text": "No",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "The whole “well did you think about why that maybe '' You completely avoiding me? I'm pretty sure the only way to connect that is that you don't like me!",
	"Choices": ["",""],
	},
	{"Name": "Ashton",
	"Position": "2",
	"Text": "Oh damn I messed up, that's not the message I was trying to convey I promise!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Uh-huh well now its mine turn to be busy, goodbye ashton",
	"Choices": ["",""],
	},
	]
