extends Node2D


var dialouge_1=[
	{
	"Name": "MC",
	"Position": "1",
	"Text": "Ashton!",
	"Choices": ["",""],
	},
	{"Name": "Ashton",
	"Position": "2",
	"Text": "Huh?",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "Fight me!",
	"Choices": ["",""],
	},
	{"Name": "Ashton",
	"Position": "2",
	"Text": "Nah",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "What?! Why not!",
	"Choices": ["",""],
	},
		{"Name": "Ashton",
	"Position": "2",
	"Text": "Don't feel like it",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "But! Please! You're really strong and I need someone to spare with!",
	"Choices": ["",""],
	},
		{"Name": "Ashton",
	"Position": "2",
	"Text": "Going to eat",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "Oh well can we fight- hey dont just leave Im talking to you!",
	"Choices": ["",""],
	},
	{"Name": "Ashton",
	"Position": "2",
	"Text": "You can come eat too you know",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "Oh well Yeah Ill follow you until you agree to be my training partner!",
	"Choices": ["",""],
	},
	{"Name": "Ashton",
	"Position": "2",
	"Text": "Do whatever you want to do",
	"Choices": ["",""],
	},
	]
