extends Node2D


var dialouge_1=[
	{
	"Name": "Arcaniea",
	"Position": "1",
	"Text": "Excuse me",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Yes, My lady, how can I help you?",
	"Choices": ["",""],
	},
	{
	"Name": "Arcaniea",
	"Position": "1",
	"Text": "I believe I may have done something that may warrant an apology from me",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Um, if you're talking about the other day then youre okay I shouldnt of-.",
	"Choices": ["",""],
	},
	{"Name": "Arcaniea",
	"Position": "1",
	"Text": "Stop talking, I would like to apologize. After talking with my brother it would seem that I was rude to you the other day.",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "(Yeah no kidding you were…) Well thank you for the apology",
	"Choices": ["",""],
	},
	{"Name": "Arcaniea",
	"Position": "1",
	"Text": "...",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "...",
	"Choices": ["",""],
	},
	{"Name": "Arcaniea",
	"Position": "1",
	"Text": "Well Im waiting",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Um… waiting for what?",
	"Choices": ["",""],
	},
	{"Name": "Arcaniea",
	"Position": "1",
	"Text": "For you to converse with me of course, thats what you were wanting to do yesterday wasnt it?",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Oh um, yeah I guess. Well um… (Well what do I do now?)",
	"Choices": ["",""],
	},
	{"Name": "Arcaniea",
	"Position": "1",
	"Text": "Well im waiting",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Whats your favorite color…?",
	"Choices": ["",""],
	},
	{"Name": "Arcaniea",
	"Position": "1",
	"Text": "Pink",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Oh, pink is nice! Mine is blue",
	"Choices": ["",""],
	},
	{"Name": "Arcaniea",
	"Position": "1",
	"Text": "Oh, I believe I read this in an etiquette book before, I am supposed to ask you what your favorite color is after you ask mine correct?",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "(I already told you mine though...)Uh well you dont have to but it makes the other person feel like you care about getting to know them too.",
	"Choices": ["",""],
	},
	{"Name": "Arcaniea",
	"Position": "1",
	"Text": "Interesting, I have never had the opportunity to ‘converse’ with someone in this matter, I am excited to learn more and be able to write down my findings on ‘casual conversation’",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Well I guess im glad to help?",
	"Choices": ["",""],
	},
]

var after_choice_1 = [
	{
	"Name": "Arcaniea",
	"Position": "1",
	"Text": "Good Day",
	"Choices": ["",""],
	},
]

var after_choice_2 = [
	{
	"Name": "Arcaniea",
	"Position": "1",
	"Text": "For what reason were you searching for me?",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "No I was just maybe hoping we could just converse a bit, I mean were fighting alongside each other all the time and strategizing but we never converse with just each other.",
	"Choices": ["",""],
	},
	{"Name": "Arcaniea",
	"Position": "1",
	"Text": "Im not sure why it is we would need to converse at any other time than required. Unless you need something from me, so out with it already what is it you want?",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Uh I dont want anything from you other than to know more about you.",
	"Choices": ["",""],
	},
	{"Name": "Arcaniea",
	"Position": "1",
	"Text": "I would appreciate it if you stop with this act, I have had many people who tried this same act, in the end they have always wanted something. So what is it? Power, Money, my companionship? ",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "I don't want anything from you. I don't need your power or your wealth or whatever ‘companionship’ from you is. I was just trying to be friendly but I can see you don't want that, so i'm going to leave now",
	"Choices": ["",""],
	},
	
]
