extends Node2D


var dialouge_1=[
	{
	"Name": "Arcaniea",
	"Position": "1",
	"Text": "Hello MC! lets converse again. I just obtained the most interesting set of chemicals for my experiments (Continues to go on and on)",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "(Arcaniea seems so excited to be talking about this, and she keeps on searching me out to talk) Haha You know its nice to see you so happy Arcaniea!",
	"Choices": ["",""],
	},
	{
	"Name": "Arcaniea",
	"Position": "1",
	"Text": "Huh? I am confused, I look happy?",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Yeah! You’ve seemed so happy each time we talk lately, I may not understand a lot of what you’re talking about but Im just happy that you seem to be in such high spirits lately",
	"Choices": ["",""],
	},
	{"Name": "Arcaniea",
	"Position": "1",
	"Text": "Uh… oh, well um im not exactly sure how I am supposed to respond to that.",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Haha thats okay Arcaniea that happens to everybody, I guess its at least nice that youre not telling me to go away anymore.",
	"Choices": ["",""],
	},
	{"Name": "Arcaniea",
	"Position": "1",
	"Text": "I am still genuinely sorry for the way I treated you that day. You have helped to open my eyes to a new world, before talking to you I thought I understood people very well. Every person that has ever spoke to me besides my brother or you has always wanted something from me. ",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Oh…",
	"Choices": ["",""],
	},
	{"Name": "Arcaniea",
	"Position": "1",
	"Text": "My family has quite a bit of wealth and power, and as a daughter of the head of the family I'm usually seen as a resource to most. People who want money, fame, or those who desire my hand in marriage.",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Oh wow, Im really sorry Arcaniea, I never even thought about it like that. It… must of been really lonely not having anyone to talk to.",
	"Choices": ["",""],
	},
	{"Name": "Arcaniea",
	"Position": "1",
	"Text": "Oh it was okay, Ive always had my brother. He’s on the same level as me, hes never needed anything from me but yet he still talked to me and allowed me to speak about all the things that interest me.",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Well Im really glad you had him, but just so you know Im here too. ",
	"Choices": ["",""],
	},
	{"Name": "Arcaniea",
	"Position": "1",
	"Text": "I thank you very much for that. I fully understand the fact that I can be a, what do people call me? Insufferable and rude woman, and so I feel gratitue to you for putting up with that.",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Dont listen to all that, the people who say that kind of stuff are the same people who want nothing but your money. Ill be honest that sometimes you can be a bit blunt, but theres nothing wrong with that.",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Thank you MC, I hope you’ll continue to converse with me for a long time.",
	"Choices": ["",""],
	},
]

