extends Node2D


var dialouge_1=[
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "Good afternoon MC, how are you fairing this afternoon?",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Oh uh… Good evening My Lady, I'm doing quite well, how isith yours? (I think im getting this whole fancy talk down)",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "...",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "Mine ‘isith’ is going quite well. I thought I would take a stroll through the gardens after my Intermediate Arcane Elements lesson. It's best to go into my advanced applied political morality class with a clear mind.",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Oh yeah I hate when my head isn't clear for my applied moriarty politics lesson",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "...",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "*Sweating* Uh well My Lady you seem to rarely take a break, you alway seem to be going to do the next complicated meeting or lesson, do you ever just take a day off?",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "Of course I allocate time between my lessons for walks through the garden in order to get some fresh air, and then meal times",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Well that's good but do you ever take vacations? ",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "Crown princess’s dont really take vacations",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Oh… but dont you own holiday palaces and stuff like that?",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "Why of course, we have the Sea glass palace located on the crescent coast in our vassal state of Eyrenor, I have visited there quite often.",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Oh that's cool! Did you swim while you were there?",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "No",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Uh then what did you do?",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "I met with foreign Politicians",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Oh, how relaxing…",
	"Choices": ["",""],
	},
]
