extends Node2D


var dialouge_1=[
	{"Name": "MC",
	"Position": "2",
	"Text": "Fae? What’re you doing at the lake so late?",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "I could ask you the same MC, I did not think anyone would be out here.",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "I was doing some guard rounds, wait have you been crying? Are you okay ?!",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "Excuse me? No of course I haven't been crying, I was just taking time for myself, like you said to do!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Fae, I know you’re lying",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "...",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "...",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "Fine. I was crying.",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "About what? Talk to me",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "It's complicated and not an issue of yours to be concerned with",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "I'm concerned about it because it concerns you though, so tell me",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "Its just… all too much sometimes",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "I am the crown princess currently because my uncle, the emperor, refuses to marry and have a child. He fully supports my claim to the throne.",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "But there is so much uncertainty in my life. With one decision by him my entire life could crumble before my eyes",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "Everything I have ever done or worked for, destroyed in seconds.",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "The only thing in my life that is certain is myself, the only person it feels like I can fully rely on is myself.",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "So you see, I cannot afford to take breaks in this life, so the moment I slip I may have everything taken from me.",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "You know Fae to me it looks like you’re stressing yourself out about all the wrong stuff.",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "So what if you’re not the crown princess, that doesn't take away the value of ANYTHING you've done and accomplished, regardless of title you will always be the amazingly talented fae I know.",
	"Choices": ["",""],
	},
		{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "Mc… I  don't think I have anyone ever care about Fae, instead of the ‘crowned princess’",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Well hey I'm here now so",
	"Choices": ["",""],
	},
		{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "*laughs* I suppose you are",
	"Choices": ["",""],
	},

]
