extends Node2D


var dialouge_1=[
	{"Name": "MC",
	"Position": "2",
	"Text": "Ah Good morning my Lady, are you taking a tea break?",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "Ah, MC! I am as you would say taking a break, would you like to join me?",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Of course! I have some fresh tea leaves I just got gifted by one of the villagers, would you like to try it?",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "…(looking focused at a giant stack of papers)",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Fae you can't call it a break if you're doing work during the break!",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "OH! I'm so very sorry MC, that is terribly rude of me. I am just trying to memorize all of the nobles that will be attending the royal banquet next week.",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Fae that has to be so many people, why would you do that to yourself??",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "It is my responsibility to take such burdens upon myself, I am the crown princess and as such I must make myself a good example for all of my people.",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "And how does memorizing everyones name help to better the lives of the people exactly?",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "Well then I am able to make more positive relationships with all of the noble counsel, it helps to make every individual I meet feel special",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Well I mean or you could just ask for an introduction, wouldn't allowing them to introduce themselves make it so you can get to know each other better ",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "Uh- well I never thought about it like that…",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Fae I think you need to take more time for yourself, thats just as important to improving ourselves",
	"Choices": ["",""],
	},
	{
	"Name": "Faerieth",
	"Position": "1",
	"Text": "I will take your words into consideration MC, Thank you for your advice and your time today",
	"Choices": ["",""],
	},
]
