extends Node2D


var dialouge_1=[
	
	{"Name": "MC",
	"Position": "2",
	"Text": "Man… I'm hungry",
	"Choices": ["",""],
	},
	{
	"Name": "Incria",
	"Position": "1",
	"Text": "MC! Look, I handmade your favorite dish for you!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "DEAR AEOS, Incria where did you come from?! You scared the soul out of me!",
	"Choices": ["",""],
	},
	{
	"Name": "Incria",
	"Position": "1",
	"Text": "What?! Where did your soul go? I will have to go get it back!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Not literally Incria, but jeez you walk so quite",
	"Choices": ["",""],
	},
	{
	"Name": "Incria",
	"Position": "1",
	"Text": "Well of course I do! My goddess, Soircia, is the goddess of trickery, stealth, and mischief, if I wasn't stealthy, how could I call myself a cleric of her name!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Oh yeah I guess I never knew which god you followed Incria, but that sounds pretty on brand for you.",
	"Choices": ["",""],
	},
	{
	"Name": "Incria",
	"Position": "1",
	"Text": "I will take that as a compliment! You know she's the greatest, she's guided me down my path for my whole life! She even led me to you!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Uh she led you to me?",
	"Choices": ["",""],
	},
	{
	"Name": "Incria",
	"Position": "1",
	"Text": " Hehe I cannot tell my lady's secrets! But you need to eat your food before it gets too cold!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Oh well thank you, wow! This is some of the best udon I’ve ever had!",
	"Choices": ["",""],
	},
	{
	"Name": "Incria",
	"Position": "1",
	"Text": "Im glad! Why don't we go on a walk by your favorite spots after this to take a break as well?",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "You know you're really thoughtful of me, Incria, its pretty nice.",
	"Choices": ["",""],
	},
	{
	"Name": "Incria",
	"Position": "1",
	"Text": "Does that mean you’ll marry me?!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "*Sweats*",
	"Choices": ["",""],
	},
	
]
