extends Node2D


var dialouge_1=[
	
	{"Name": "MC",
	"Position": "2",
	"Text": "INCRIA!",
	"Choices": ["",""],
	},
	{
	"Name": "Incria",
	"Position": "1",
	"Text": "H-hey mc, you okay?",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Am I okay!? Are you Ok?! You just got stabbed! Why did you get in front of him like that, he was going for me!",
	"Choices": ["",""],
	},
	{
	"Name": "Incria",
	"Position": "1",
	"Text": "Ha… because I love you of course!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Incria! Please don't place yourself in danger like that!",
	"Choices": ["",""],
	},
	{
	"Name": "Incria",
	"Position": "1",
	"Text": "Nope!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "What? Why?!",
	"Choices": ["",""],
	},
	{
	"Name": "Incria",
	"Position": "1",
	"Text": "Because this is the most care you've shown for me yet, and it prove how much you really like me!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Incria you don't have to get hurt for me to care about you!",
	"Choices": ["",""],
	},
	{
	"Name": "Incria",
	"Position": "1",
	"Text": " Then marry me! If not, I will keep on following you. Giving you things, and placing myself in between you and the bad guys recklessly until you accept!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Dear Aeos Incria, I can't promise anything right now but I promise to consider it if you promise ti stay safe!",
	"Choices": ["",""],
	},
	{
	"Name": "Incria",
	"Position": "1",
	"Text": "Yay! Deal!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "You're way too cheerful for someone whos bleeding out…",
	"Choices": ["",""],
	},
	
	
]
