extends Node2D


var dialouge_1=[
	{
	"Name": "Incria",
	"Position": "1",
	"Text": "OH! MC! I finally found you. I have been searching far and wide for you.",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Oh… *sweats* Hi Incria, how can I help you?",
	"Choices": ["",""],
	},
	{
	"Name": "Incria",
	"Position": "1",
	"Text": "Well you slipped away from me last time we were talking so I thought I would come Find you again!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Oh well I actually have some other things I need to be attending to-",
	"Choices": ["",""],
	},
	{
	"Name": "Incria",
	"Position": "1",
	"Text": "I mean you left at the most important part of my proposition! Where the two of us will be living after we get married in the blue crystalline caverns of mount Obor!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Incria I don't think we need to have this conversation, were not getting married",
	"Choices": ["",""],
	},
	{
	"Name": "Incria",
	"Position": "1",
	"Text": "Well of course we do! We aren't getting married yet but remember the timeline I setup was getting married after we finish up this war, then you’ll fall madly in love with me and then we get married after we join a pirate ship and sail across the Silkin ocean!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Uh Incria why are you so set on marrying me and doing all of this stuff with me? I mean we met a couple of weeks ago. You barely know me.",
	"Choices": ["",""],
	},
	{
	"Name": "Incria",
	"Position": "1",
	"Text": "I can't tell you my secrets! But also I know everything about you! I know that your favorite food is Kimchi Udon. Your favorite color is blue, and you always sleep on your right side!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "",
	"Choices": ["",""],
	},
]
