extends Node2D


var dialouge_1=[
		{
	"Name": "Odrahn",
	"Position": "1",
	"Text": "MC! The owlcat they woke up! Come quick!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Oh! I'm coming!",
	"Choices": ["",""],
	},
	{"Name": "Owl Cat",
	"Position": "2",
	"Text": "HISSSSS",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "AH! They're not very happy to be awake I guess!",
	"Choices": ["",""],
	},
		{
	"Name": "Odrahn",
	"Position": "1",
	"Text": "Hey little one it's okay we're not going to hurt you, this is the person who rescued you!",
	"Choices": ["",""],
	},
	{"Name": "Owl Cat",
	"Position": "2",
	"Text": "*Begins sniffing and rubbing up against mcs legs*",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Oh yeah I forgot you can actually talk to animals right?",
	"Choices": ["",""],
	},
		{
	"Name": "Odrahn",
	"Position": "1",
	"Text": "I have a better ability to understand them due to my druidic magics nature yes, but I believe all people are able to communicate with animals, they just don't try hard enough",
	"Choices": ["",""],
	},
	{"Name": "Owl Cat",
	"Position": "2",
	"Text": "*Laying down in MCS laps*",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "I guess thats just how a lot of people are, too many people with communication issues, or a lack of trying enough to even know they have them",
	"Choices": ["",""],
	},
		{
	"Name": "Odrahn",
	"Position": "1",
	"Text": "I believe that the issue with communication with animals is difficult, because if we were all able to communicate as well as I we would have a lot less issues in the world, heck this war may not even be happening.",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Hmm you know you go way deeper than I first thought Odrahn!",
	"Choices": ["",""],
	},
		{
	"Name": "Odrahn",
	"Position": "1",
	"Text": "h-Uh! W-hats doe-s that me-an??",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Hehe dont worry about it!",
	"Choices": ["",""],
	},
	]
