extends Node2D


var dialouge_1=[
		{
	"Name": "Odrahn",
	"Position": "1",
	"Text": "MC! It looks like you and the owlcat are making fast friends!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Yep! They're training with me now, I think im going to keep them and take care of them from now on!",
	"Choices": ["",""],
	},
	{"Name": "Obrahn",
	"Position": "2",
	"Text": "Thats amazing! I'm glad that they'll have someone to give them a much better life.",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Hey! Its not just me we both saved them so were in this together!",
	"Choices": ["",""],
	},
		{
	"Name": "Odrahn",
	"Position": "1",
	"Text": "What do you mean in it together?!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Haha you know exactly what I mean! And Im going to keep on bringing you every injured animal I find! Well make the world better for a bunch of animals and people!",
	"Choices": ["",""],
	},
		{
	"Name": "Odrahn",
	"Position": "1",
	"Text": "Oh geez I don't know if i'm ready to sign up for that yet!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Well thats too bads, you're stuck with me now, and Im not going away anytime soon! ",
	"Choices": ["",""],
	},
		{
	"Name": "Odrahn",
	"Position": "1",
	"Text": "Haha I wouldn't have it any other way…",
	"Choices": ["",""],
	},
	]
