extends Node2D


var dialouge_1=[
		{
	"Name": "MC",
	"Position": "1",
	"Text": "Velouria are you okay!?",
	"Choices": ["",""],
	},
	{"Name": "Velouria",
	"Position": "2",
	"Text": "Ugh… uh I think so",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "You got a bit pretty bad by that giant wolf! I don't even know how you killed it!",
	"Choices": ["",""],
	},
	{"Name": "Velouria",
	"Position": "2",
	"Text": "Yeah the wound looks pretty bad, we should probably set up camp somewhere near so I can clean it.",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "Okay! I'll find a spot right no- Veloria what happened to your bow? Its magical aura is off the charts right now!",
	"Choices": ["",""],
	},
	{"Name": "Velouria",
	"Position": "2",
	"Text": "Let's talk about it after I sit down, I'm losing a lot of blood right now.",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "Alright, how are you feeling?",
	"Choices": ["",""],
	},
	{"Name": "Velouria",
	"Position": "2",
	"Text": "Much better now",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "...",
	"Choices": ["",""],
	},
	{"Name": "Velouria",
	"Position": "2",
	"Text": "...",
	"Choices": ["",""],
	},
	{
	"Name": "Velouria",
	"Position": "1",
	"Text": "Well I guess you wanna know the story on the bow?",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Yeah kinda",
	"Choices": ["",""],
	},
	{
	"Name": "Velouria",
	"Position": "1",
	"Text": "*Sigh* Well, to understand that well have to start from the beginning",
	"Choices": ["",""],
	},
	{
	"Name": "Velouria",
	"Position": "1",
	"Text": "I was born and raised by my parents on the Obor mountain range, we were apart of a group of hunters that would take on bounties for certain game.",
	"Choices": ["",""],
	},
	{
	"Name": "Velouria",
	"Position": "1",
	"Text": "That's where I learned most of my fighting talents, I loved adventuring through the woods with everyone.",
	"Choices": ["",""],
	},
	{
	"Name": "Velouria",
	"Position": "1",
	"Text": "But not all stories have happy endings. One day I came back from gathering berries only to find my entire group dead, the only sign I could find of who killed them was this odd symbol on a copper coin.",
	"Choices": ["",""],
	},
	{
	"Name": "Velouria",
	"Position": "1",
	"Text": "I tried to make it to a town to get help, and on the way I managed to fall into some sort of ancient ruin.",
	"Choices": ["",""],
	},
	{
	"Name": "Velouria",
	"Position": "1",
	"Text": "Looking back I think I was meant to end up there, after following my gut I ended up finding this bow.",
	"Choices": ["",""],
	},
	{
	"Name": "Velouria",
	"Position": "1",
	"Text": "I believe It's what people call an oath bow, It's really handy when hunting down a specific target.",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "...",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "Wow… okay that was a lot",
	"Choices": ["",""],
	},
	{
	"Name": "Velouria",
	"Position": "1",
	"Text": "Yeah sorry",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "Im sorry Velouria,  that's terrible",
	"Choices": ["",""],
	},
	{
	"Name": "Velouria",
	"Position": "1",
	"Text": "Hey now let's not get all doom and gloom, just promise from now on well be the greatest pof hunting partners, since you know everything about me and all",
	"Choices": ["",""],
	},
	{
	"Name": "MC",
	"Position": "1",
	"Text": "Of course Velouria! I promise to always go with you from now on",
	"Choices": ["",""],
	},
	
	
	
]

