extends Node2D


var dialouge_1=[
		{
	"Name": "Velouria",
	"Position": "1",
	"Text": "How are you feeling about that hunting session we went to? Are you feeling sore?",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "...",
	"Choices": ["",""],
	},
	{
	"Name": "Velouria",
	"Position": "1",
	"Text": "Think you feel up to going again??",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Velouria I dont think Ive mentally recovered from your ‘training’. Usually some light training does not consist of trekking through the mountains for a week straight hunting down some random stag.",
	"Choices": ["",""],
	},
	{
	"Name": "Velouria",
	"Position": "1",
	"Text": "Come on, don't be so stuffy",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "I dont think Im being stuffy, just really tired! ",
	"Choices": ["",""],
	},
	{
	"Name": "Velouria",
	"Position": "1",
	"Text": "Hey we got a ton of reward money for bringing in that hunt though, I got to buy a bunch of new equipment with it and Im ready to go again!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "With all that money you didnt go out and buy a new bow? It looks like youve had the one youve been using for a really long time.",
	"Choices": ["",""],
	},
	{
	"Name": "Velouria",
	"Position": "1",
	"Text": "O-oh well… this bow is special, I cant just replace it. Its my weapon for life!",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "But what if it breaks? Weapons don't last forever, i'm kind of worried about you being defenseless on one of these absurdly long hunting trips now.",
	"Choices": ["",""],
	},
	{
	"Name": "Velouria",
	"Position": "1",
	"Text": "You don't have to worry about that, this bow isn't going to break so easily, it's pretty special.",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "Oh, is it enchanted? I didn't get any magical senses from it so I was just assuming it was normal.",
	"Choices": ["",""],
	},
	{
	"Name": "Velouria",
	"Position": "1",
	"Text": "Its something like that, how about this, if you promise to to go with me on another hunting trip maybe I'll tell you more about it",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "I have to go on another one for a chance of you telling me?",
	"Choices": ["",""],
	},
	{
	"Name": "Velouria",
	"Position": "1",
	"Text": "Yep! Some good old gambling, what do you think about your odds?",
	"Choices": ["",""],
	},
	{"Name": "MC",
	"Position": "2",
	"Text": "*Sigh* I guess it's better than nothing, when are we leaving?",
	"Choices": ["",""],
	},
		
	
]

